name: enough_convert
description: Support for character encodings / charsets / codecs missing from `dart:convert` - ISO 8859 / Latin, Windows, DOS, GBK, Big5, and KOI8 R/U.
version: 2.0.0
homepage: https://github.com/rk0cc/enough_convert
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ^1.9.1
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
